Dev
Troon-Technologies-LLC/TriQuetaSmartContract pull request #7
Opened 2022-06-25 18:12 UTC by saadtroon

I have added following functionality in Contract:
* updateMutableData
* lockTemplate
* isTemplateLocked
* getImmutableData
* getMutableData

2022-06-29 13:50 UTC, ObjectPlayer requested changes
@saadtroon Good Work, kindly work on following updates

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +        init(brandId: UInt64, schemaId: UInt64, maxSupply: UInt64, immutableData: {String: AnyStruct}, mutableData: {String: AnyStruct}?) {
@saadtroon do `maxSupply: UInt64` also accept nil ?

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +        pub fun lockTemplate(status: Bool){
@saadtroon `lockTemplate` method, does not require any argument it just lock template, if it is unlocked (which is by default)

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
>              pre {
@saadtroon If template is locked, than you can increment the supply. Kindly add that condition in the pre-condition

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +                self.locked != true: "template is locked"
in case of Bool, you don't need to check if it is `!=` or `==`  to desired out. Just add condition like 

` !self.locked : "template is locked" `

if it is working, than replace it but confirm it before implementing it

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +                status != false: "invalid status"
we don't need any `status` in this method

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
>              TriQuetaNFT.totalSupply = TriQuetaNFT.totalSupply + 1
@saadtroon here you should check, if template is locked or not. If it is locked than we can't create NFT.

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +        init(templateID: UInt64, mintNumber: UInt64, immutableData: {String: AnyStruct}?) {
@saadtroon do we need to pass `mintNumber` here ? we can get `mintNumber` from template using `templateID`

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +        pub fun lockTemplateById(templateId: UInt64, status: Bool)
@saadtroon we don't need to pass the `status` here

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
>          pub fun createTemplate(brandId: UInt64, schemaId: UInt64, maxSupply: UInt64, immutableData: {String: AnyStruct}) {
@saadtroon while creating template, we also need to pass `mutableData`

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +                TriQuetaNFT.allTemplates[templateId]!.locked != true: "You are not authorized because the template is locked"
@saadtroon same here, also do we need to add `locked` condition here if we already added above ?

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
> +            TriQuetaNFT.allTemplates[templateId]!.lockTemplate(status: status)
We don't need to pass the `status` here

2022-06-29 13:50 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
>      pub fun createAdminResource(): @AdminResource {
We don't need that method as public, you can discuss with @Nasir-Ali-Shah and use different method as we are using in xg

2022-06-30 12:51 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
> +    pub event NFTBorrowed(id: UInt64)
no. removing this

2022-06-30 22:17 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
> +        init(brandId: UInt64, schemaId: UInt64, maxSupply: UInt64, immutableData: {String: AnyStruct}, mutableData: {String: AnyStruct}?) {
Yes

2022-06-30 22:39 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
>          pub fun createTemplate(brandId: UInt64, schemaId: UInt64, maxSupply: UInt64, immutableData: {String: AnyStruct}) {
That is optional but i can add other transaction for mutableData

2022-07-02 01:03 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
>              destroy oldToken
resource has to be in storage, to show owner, if you withdraw, then emit event, then deposit item, it can be nil
you can see nbatopshot pub fun deposit for reference
            // Only emit a deposit event if the Collection 
            // is in an account's storage
            if self.owner?.address != nil {
                emit Deposit(id: id, to: self.owner?.address)

2022-07-02 01:09 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
> +                TriQuetaNFT.allTemplates[templateId]!.locked != true: "You are not authorized because the template is locked"
done

2022-07-02 01:10 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
> +            TriQuetaNFT.allTemplates[templateId]!.lockTemplate(status: status)
removed

2022-07-04 06:46 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
>              pre {
Done

2022-07-04 06:46 UTC, saadtroon commented on contracts/TriQuetaNFT.cdc
>              TriQuetaNFT.totalSupply = TriQuetaNFT.totalSupply + 1
done

2022-07-05 08:06 UTC, ObjectPlayer requested changes
Thanks @saadtroon for all the changes, just a minor change request kindly work on that and complete it. Remaining stuff is good.

2022-07-05 08:06 UTC, ObjectPlayer commented on contracts/TriQuetaNFT.cdc
>          pub fun createTemplate(brandId: UInt64, schemaId: UInt64, maxSupply: UInt64, immutableData: {String: AnyStruct}) {
Yes it is optional, that's why. If user want to add mutable data he can add it, otherwise it will be nil. But if your method does not support it, than how you can create a new transaction ? In that case you need to create a separate method. 

Therefore, just add mutabledata in that method as optional and pass as it is

2022-07-05 11:38 UTC, ObjectPlayer commented
Good Work @saadtroon

2022-07-05 11:42 UTC, merged